Remove caches from badger and kvs
hyperledger-labs/fabric-smart-client pull request #323
Opened 2022-07-26 11:25 UTC by mbrandenburger

- Remove GetCachedRangeIterator
- Badger autoclean
- Add simple badger benchmark
- KVS: remove txstore cache

Signed-off-by: Marcus Brandenburger <bur@zurich.ibm.com>

2022-07-27 05:56 UTC, adecaro commented
@mbrandenburger , could you already prepare a PR that updates the token-sdk given that it depends on API that this PR removes?

2022-07-27 10:43 UTC, mbrandenburger commented
> @mbrandenburger , could you already prepare a PR that updates the token-sdk given that it depends on API that this PR removes?

Here the PR on the token-sdk. CI runs successfully https://github.com/hyperledger-labs/fabric-token-sdk/pull/311

2022-07-27 12:48 UTC, adecaro requested changes

2022-07-27 12:48 UTC, adecaro commented on platform/fabric/core/generic/vault.go
> -	if cacheSize > 0 {
why removing this? Without this cache we pay a huge penalty.

2022-07-27 12:48 UTC, adecaro commented on platform/view/services/db/db.go
> -func unregisterAllDrivers() {
how is this part of this PR?

2022-07-27 12:48 UTC, adecaro commented on platform/view/services/kvs/kvs.go
> -	// is in cache?
why removing this cache?

2022-07-28 04:51 UTC, adecaro approved these changes

2022-07-28 04:53 UTC, adecaro approved these changes

2022-07-28 04:53 UTC, adecaro commented on platform/view/services/db/driver/badger/badger.go
> +func autoCleaner(db *badger.DB) {
What about additing a description here? Why 5 mins and 0.7?

2022-07-28 05:51 UTC, adecaro requested changes

2022-07-28 05:51 UTC, adecaro commented on platform/view/services/db/driver/badger/badger.go
> +			if err == nil {
does this mean that if no error happens, RunValueLogGC is called continuously? 
Should `again` come before the for?

2022-07-28 12:12 UTC, adecaro approved these changes

2022-07-28 12:13 UTC, merged