Reduce staticcheck warnings (SA1019)
hyperledger-labs/fabric-smart-client pull request #328
Opened 2022-07-27 09:36 UTC by alexandrosfilios

As part of issue #50, removed warnings related to:
* SA1019: removed deprecated grpclog.SetLogger and ptypes

Signed-off-by: Alexandros Filios <alexandros.filios@ibm.com>

2022-07-27 14:31 UTC, mbrandenburger requested changes
Thanks

2022-07-27 14:31 UTC, mbrandenburger commented on platform/view/services/client/view/client.go
> +
empty line

2022-07-27 14:31 UTC, mbrandenburger commented on integration/fabric/atsa/chaincode/chaincode/asset_transfer.go
> +	if err = txTimestamp.CheckValid(); err != nil {
```suggestion
	if err := txTimestamp.CheckValid(); err != nil {
```

2022-07-27 14:31 UTC, mbrandenburger commented on integration/fabric/atsa/chaincode/chaincode/asset_transfer_queries.go
> +		if err = response.Timestamp.CheckValid(); err != nil {
```suggestion
		if err := response.Timestamp.CheckValid(); err != nil {
```

2022-07-27 14:31 UTC, mbrandenburger commented on platform/view/services/client/view/client.go
> +	if err = ts.CheckValid(); err != nil {
```suggestion
	if err := ts.CheckValid(); err != nil {
```

2022-07-27 14:31 UTC, mbrandenburger commented on platform/view/services/server/view/marshal.go
> +
Please remove empty line and run goimports again

2022-07-27 14:31 UTC, mbrandenburger commented on platform/view/services/server/view/marshal.go
> +	if err = ts.CheckValid(); err != nil {
```suggestion
	if err := ts.CheckValid(); err != nil {
```

2022-07-29 05:47 UTC, adecaro approved these changes
LGTM

2022-07-29 10:04 UTC, mbrandenburger approved these changes

2022-07-29 10:04 UTC, merged