fabric-sdk: cleanup ordering connection on failure + retry #377
hyperledger-labs/fabric-smart-client pull request #379
Opened 2022-08-27 05:18 UTC by adecaro

Signed-off-by: Angelo De Caro <adc@zurich.ibm.com>

2022-08-28 23:33 UTC, yacovm approved these changes
seems fine. Shame there are no unit tests though.

2022-08-29 09:48 UTC, mbrandenburger requested changes

2022-08-29 09:48 UTC, mbrandenburger commented on docs/fabric-sdk.md
> +    broadcast:
as the comment already describes ... why don't we just call it `ordering` as this is the fabric term?

2022-08-29 09:48 UTC, mbrandenburger commented on integration/nwo/fabric/topology/core_template.go
> +      retryInternal: 3s
see comment above

2022-08-29 11:52 UTC, mbrandenburger approved these changes

2022-08-29 12:15 UTC, merged