fabric platform driver mgmt refactor
hyperledger-labs/fabric-smart-client pull request #655
Opened 2024-08-29 05:50 UTC by adecaro

This PR does the following: It refactors the fabric platform driver management to have each driver decide on the dependency to set. Dig must be used just to provide external dependencies.

2024-08-29 07:53 UTC, mbrandenburger commented on platform/fabric/sdk/generic/providers.go
>  type ChannelHandlerProviderResult struct {
I remember that Alex suggested to keep all code that depends/uses on dig in a separate package to keep a structure where we see easily when dig is used.

@alexandrosfilios does this strategy still applies?

2024-08-30 11:00 UTC, mbrandenburger requested changes

2024-09-02 11:34 UTC, adecaro commented on docs/fabric/drivers.md
> +The Fabric platform consists of a [`Fabric API`](https://github.com/hyperledger-labs/tree/main/fabric-smart-client/platform/fabric)
okay

2024-09-02 11:44 UTC, mbrandenburger approved these changes
LGTM

2024-09-03 09:49 UTC, alexandrosfilios approved these changes
LGTM

2024-09-05 05:23 UTC, merged